# Generated by Django 5.0 on 2026-09-04 03:24
# creates migration files based on models previously defined
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='movie_images/')),
            ],
        ),
    ]
#must execute python manage.py makemigrations if Movie models are added/changed
    #python manage.py makemigrations
    #python manage.py migrate